### PR TITLE
Add t8sg and devof4

### PR DESCRIPTION
**Pull request by vladislavy**
I can't test it with Windows environment. So, it's suggested change for testing.

### CODE REVIEW

**Comment by F-D-R** [comment]
I think "t8sg" is redundant in the transmitter definitions, if you already have ".*t8sg.*".
IMO it would be more appropriate to have a separate T8SG type, because now it would be recognized as a 7E...

The patterns in the Analyze method are redundant too, the ones without the "devo" prefixes would match the devo firmwares and libraries too...

**Comment by vladislavy** [comment]
We can't use separate T8SG type since it has devo7e txid (0x7e).

"deviation-devo7e-v5.0.0-be57e84" 
without the "devo" prefixes will be compared with 
"deviation-7e-v5.0.0-be57e84"

**Comment by F-D-R** [comment]
No, I see now where I was mistaken:

The pattern "deviation-devo([^-]+)-(\\S+)\\.zip" will match "deviation-devo7e-v5.0.0-be57e84.zip" and give "7e" and "v5.0.0-be57e84" as results, however the "deviation-([^-]+)-(\\S+)\\.zip" patter while would match with the same filename, but would give "devo7e" and "v5.0.0-be57e84" as results. Only the "else if" statement prevents to finding that, so that is fine indeed.

BTW in case of the U7E, which has a filename of "deviation-devo7e-256-v5.0.0-be57e84.zip" the results would be "7e" and "256-v5.0.0-be57e84", which is not that good, I think...

**Review by F-D-R — APPROVED** [review]
I approve it, because it is definitely better then it was, but probably it will need some more refinements

**Pull request closed without merging**
