### PR TITLE
 replace direct console writing with java.util.logging facility

### PR DESCRIPTION
**Pull request by nitram509**
Summary
-----------------
This PR is intended to replace the current direct console (STDOUT) writing
of the application with proper logging facilites, based on java.util.logging.

Any feddback is welcome.

Tension/Reason
-----------------
While I was using the Deviation Uploader 0.9.0, I was irritated by various
messages in the terminal (I did run via 'java -jar ...' command).
There where messages like "here" or "tab index 1" and also some stack traces occur.
Clearly, some of these where leftovers from some debugging sessions.
Hence, I thought it would be usefull to have proper logging in place,
which also offers some "verbose" option, for more technical skilled users.
And like with any proper logging, there should be a systematic incl. time stamps,
which would allow users, to give good error reports to report back some issues.

Brief summary of changes
-------------------------------
* add .gitignore to ignore Eclipse and IntelliJ project files
* replace SNAPSHOT and switch to latest stable release Apache Commons CLI version 1.4
* replace all System.(out|err).(println|format) invocations with LOG.xxx method calls
* introduce two new command line switches '--verbose' and '--extra-verbose'.
* remove some comments (read as dead code).
* refactor commmand line parsing into separate class CommandLineHandler
* add documentation about logging into README
* fix some typos in source, comments, messages and README

### CODE REVIEW

**Review by TheRealMoeder — CHANGES_REQUESTED** [review]
I never noticed this PR, sorry for the late response. Maybe bump the minor version number due to this change? It at least changes user experience.

**Comment by nitram509** [comment]
@TheRealMoeder thanks for your feedback. I did bump up the minor version.

**Comment by PhracturedBlue** [comment]
I'd like to merge this and it generally looks fine, but there is too much functionality merged in a single patch here.
I need separate pull requests for:
 * moving cmdline code into its own class
 * adding logger (should change nothing else)
 * changing the interface to FlashIO
 * upgrading versions of dependencies (unless strictly required by one of the above)

I would have just bitten the bullet and merged it as is, but I am not sure of the ramifications of removing the `throws` modifiers on the functions in FlashIO.  It may be fine, but I don't know why I put them there, and so don't want to remove them without understanding what is going on.

**Review by PhracturedBlue — CHANGES_REQUESTED** [review]
See my other comments.  patch needs to be broken into smaller PRs

**Comment by PhracturedBlue** [comment]
FYI, I have not been active in Deviation for several years, so your patch (and everyone else's) was ignored by me.  I am now active again, and will process this quickly if you make my requested changes.

**Comment by nitram509** [comment]
Hi,

I'm sorry, but I wonder why breaking this into multiple PRs?
IMHO there is no difference, with one PR or with multiple PRs ... the result will be merged into the MASTER branch anyway.

May I ask what hinders you to merge this PR? (are there conflicts?)

**Comment by PhracturedBlue** [comment]
Because I can't debug any issues with a monolithic patch.  in pieces I can validate each part works as expected and can do bisection if needed in the future to debug regressions

**Comment by nitram509** [comment]
Thank you @PhracturedBlue and @TheRealMoeder .
Closing this PR and will create new PRs as suggested.

**Comment by nitram509** [comment]
One note, I plan to add the PR for "adding logger", once the other PRs are merged ... since they depend on each other and I don't want to run into merge conflicts.

**Pull request closed without merging**
